name = "polymir-backend"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "development"

[[r2_buckets]]
binding = "MVOX_STORAGE"
bucket_name = "polymir-mvox"

[[d1_databases]]
binding = "DB"
database_name = "polymir-db"
database_id = ""
